#!/bin/bash
#----------
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[36m"
ENDCOLOR="\e[0m"
#----------
echo -e "Usage: port-sweep [OPTION]... [ARG]..."
echo -e "Lightweight Port and Vulnerability Scanning for TCP Connection.\n"
echo -e "Available flag options. Starred one are meant to be optional\n"
echo -e "  ${GREEN}-t${ENDCOLOR}\t a full FQDN / IP Address of the target host. not supported for subnet-based scan"
echo -e "  ${GREEN}-p${ENDCOLOR}\t port number to be scanned. supported to accept combinations of single-port and ranges"
echo -e "  ${GREEN}-o ${YELLOW}**${ENDCOLOR}\t save the scan result to a specified file. saved to port-sweep/log by default"
echo -e "  ${GREEN}-s ${YELLOW}**${ENDCOLOR}\t sleep into the port that have been reached a given timeout in integer"
echo -e "  ${GREEN}-i ${YELLOW}**${ENDCOLOR}\t perform dependencies checking & installation to the system"
echo -e "  ${GREEN}-h ${YELLOW}**${ENDCOLOR}\t launch command usage for avilable flag options & examples"
echo -e "\nExamples:\n"
echo -e "  bash port-sweep ${GREEN}-i${ENDCOLOR}"
echo -e "  bash port-sweep ${GREEN}-t${ENDCOLOR} 192.168.1.100 ${GREEN}-p${ENDCOLOR} 1-100,3000-4500,8080"
echo -e "  bash port-sweep ${GREEN}-t${ENDCOLOR} api.example.com ${GREEN}-p${ENDCOLOR} 22,80,443 ${GREEN}-o${ENDCOLOR} result.log"
echo -e "  bash port-sweep ${GREEN}-t${ENDCOLOR} api.example.ac.id ${GREEN}-p${ENDCOLOR} 1-65535 ${GREEN}-o${ENDCOLOR} result.log ${GREEN}-s${ENDCOLOR} 10\n"
echo -e "Full documentation at hotpotcookie.github.io/docs/port-sweep"
echo -e "Open issues and report bugs to github.com/hotpotcookie/port-sweep"
	